<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
	</head>
	<body>
		<script>
			// 只能throw的方式抛出异常  并且只能用.catch捕获  try-catch捕获不到
			// async function foo() {
			// 	console.log(1);
			// 	throw  3;
			// }
			// 给返回的期约添加一个拒绝处理程序
			// try {
			//     foo().catch(err => console.log(err.message))
			// } catch (error) {
			//     console.log(error.message);
			// }
			// foo().catch(console.log);
			// console.log(2);
//todo 全局捕获
			//Promise.reject返回的无论是.catch还是try-catch均无法捕获
			function foo() {
				console.log(1);
				return Promise.reject(3);
				// await Promise.reject(3)
			}
			// Attach a rejected handler to the returned promise
			async function test(){
				try {
						foo().catch(e => console.log('.catch',e))
				} catch (error) {
						console.log(error);
				}
			}
			test();
			// foo().catch((e) => {
			// 	console.log(e);
			// });
			// console.log(2);
			// 1
			// 2
			// Uncaught (in promise): 3

			// async function foo() {
			// 	console.log(await Promise.resolve("foo"));
			// }
			// async function bar() {
			// 	console.log(await "bar");
			// }
			// async function baz() {
			// 	console.log("baz");
			// 	return 
			// }
			// foo();
			// bar();
			// baz();
		</script>
	</body>
</html>
